[project]
name = "timeinspector"
version = "0.1.0"
description = "A  time calculator using PyQt"
authors = [{ name = "lcwyo", email = "lancechat@yahoo.com" }]
requires-python = "~=3.13"
readme = "README.md"
dependencies = ["pyqt5~=5.15"]

[dependency-groups]
dev = [
    "ruff>=0.9.1,<0.10",
    "pyright>=1.1.391,<2",
]

[tool.uv]
package = false

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 88
exclude = ["venv", ".venv"]
# Add specific rule settings as needed


