# -*- coding: utf-8 -*-
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""



from setuptools import setup

APP = ['timeInspector.py']
APP_NAME = "Time Inspector"
DATA_FILES = ["./res/img/kmf.png", "res/img/bell.png", "./res/img/inspector.png"]
OPTIONS = { 'argv_emulation': True,
            'iconfile' : './res/img/clock-icon.icns',
            'plist': {
            'CFBundleName': APP_NAME,
            'CFBundleDisplayName': APP_NAME,
            'CFBundleGetInfoString': "Time Inspector",
            'CFBundleIdentifier': "net.chatwell.osx.timeinspector",
            'CFBundleVersion': "0.2.1",
            'CFBundleShortVersionString': "0.2.1",
            'NSHumanReadableCopyright': u"Copyright © 2019, Lance Chatwell, All Rights Reserved"
            }
           }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
